global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: mtail
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - /etc/prometheus/mtail.yaml
